appname: "footytips"

layout: "footytips"

session: simple

charset: "UTF-8"

template_toolkit: TT


template: "template_toolkit"
engines:
   template_toolkit:
      encoding:  'utf8'
      start_tag: '[%'
      end_tag:   '%]'



plugin:
   Database:
      driver: 'SQLite'
      database: 'footydata'
      host: 'localhost'
      username: ''
      password: ''
      connection_check_threshold: 10
