# configuration file for production environment
session: "cookie"
session_cookie_key: "kjsdf07232Gjf0szk+lj12*&(@*jk"

# only log warning and error messsages
log: "warning"

# log message to a file in logs/
logger: "file"

# don't consider warnings critical
warnings: 0

# hide errors 
show_errors: 0 

# cache route resolution for maximum performance
route_cache: 1

appname: "footytips"

layout: "footytips"

charset: "UTF-8"

template_toolkit: TT

template: "template_toolkit"

engines:
   template_toolkit:
      encoding:  'utf8'
      start_tag: '[%'
      end_tag:   '%]'

